{% set version = "0.1.1.0" %}

package:
  name: evalhyd-python
  version: {{ version }}

source:
  url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/evalhyd-python/-/archive/v{{ version }}/evalhyd-python-v{{ version }}.tar.gz
  sha256: ac451d46fa451f84c620028fe25acb153bb7ab851848481e0994303817a2ba9f

build:
  number: 0
  script_env:
    - CPPFLAGS=-D_LIBCPP_DISABLE_AVAILABILITY -std=c++17    # [osx]
    - EVALHYD_PYTHON_VENDOR_XTL=FALSE
    - EVALHYD_PYTHON_VENDOR_XTENSOR=FALSE
    - EVALHYD_PYTHON_VENDOR_XTENSOR_PYTHON=FALSE
    - EVALHYD_PYTHON_VENDOR_EVALHYD_CPP=FALSE
  script:
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make                                                  # [unix]
    - ninja                                                 # [win]
    - python
    - pybind11
    - setuptools
    - pip
  host:
    - python
    - pip
    - setuptools
    - numpy
    - pybind11
    - xtl >=0.7.5
    - xtensor >=0.24.6
    - xtensor-python >=0.26.1
    - libevalhyd ==0.1.1
  run:
    - python
    - numpy

test:
  imports:
    - evalhyd
  commands:
    - python -c "import evalhyd; assert evalhyd.__version__ == '{{ version }}'"
    - python -c "import evalhyd; import numpy; assert evalhyd.evald(numpy.array([1, 2, 3]), numpy.array([1, 2, 3]), ['NSE'])[0][0, 0, 0] == 1"
  requires:
    - pip

about:
  home: https://hydrogr.github.io/evalhyd
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENCE.rst
  summary: Python bindings for evalhyd, a C++ library to evaluate streamflow predictions
  description: |
    A Python package to evaluate deterministic and probabilistic 
    streamflow predictions
  doc_url: https://hydrogr.github.io/evalhyd/python
  dev_url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/evalhyd-python

extra:
  recipe-maintainers:
    - fbourgin
    - ThibHlln
